#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

source "vendor/github.com/reconquest/import.bash/import.bash"

import:source "github.com/reconquest/hastur"
import:source "github.com/reconquest/containers"
import:source "github.com/reconquest/progress"
import:source "github.com/reconquest/test-runner"
import:source "github.com/reconquest/tests.sh"
import:source "github.com/reconquest/go-test"

import:include tests/ssh.sh
import:include tests/build.sh
import:include tests/orgalorg.sh

which brctl >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "missing dependency: brctl (bridge-utils)"
    exit 1
fi

which hastur >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "missing dependency: hastur"
    exit 1
fi

test-runner:set-custom-opts \
    --keep-containers \
    --keep-images \
    --containers-count:

test-runner:handle-custom-opt() {
    case "$1" in
        --keep-containers)
            containers:keep-containers
            hastur:keep-images
            ;;

        --keep-images)
            hastur:keep-images
            ;;

        --containers-count)
            containers:set-count "$2"
            ;;
    esac
}

progress:spinner:new _progress_spinner

test-runner:progress() {
    if [ "${1:-}" = "stop" ]; then
        printf " ok."
    else
        progress:spinner:spin "$_progress_spinner" > /dev/null
    fi
}

:init() {
    go-test:set-output-dir "$(readlink -f .)"
    go-test:build orgalorg

    hastur:init openssh,pam,util-linux,tar,iproute2,sudo,sed,procps-ng
}

:cleanup() {
    containers:wipe

    hastur:destroy-root

    progress:spinner:stop "$_progress_spinner"

    go-test:merge-coverage
}

:init 2> >(progress:spinner:spin "$_progress_spinner" > /dev/null)

trap :cleanup EXIT

test-runner:run "${@}"
